# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_Admin(object):
    def setupUi(self, Main_Admin):
        Main_Admin.setObjectName("Main_Admin")
        Main_Admin.resize(1468, 1148)
        self.centralwidget = QtWidgets.QWidget(parent=Main_Admin)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(22, 105, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_home.setFont(font)
        self.btn_home.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_home.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.btn_room = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_room.setGeometry(QtCore.QRect(22, 156, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_room.setFont(font)
        self.btn_room.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_room.setObjectName("btn_room")
        self.btn_customer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_customer.setGeometry(QtCore.QRect(22, 207, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_customer.setFont(font)
        self.btn_customer.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_customer.setObjectName("btn_customer")
        self.btn_contract = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_contract.setGeometry(QtCore.QRect(22, 258, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_contract.setFont(font)
        self.btn_contract.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_contract.setObjectName("btn_contract")
        self.btn_eIndex = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_eIndex.setGeometry(QtCore.QRect(22, 309, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eIndex.setFont(font)
        self.btn_eIndex.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_eIndex.setObjectName("btn_eIndex")
        self.btn_bill = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_bill.setGeometry(QtCore.QRect(22, 360, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bill.setFont(font)
        self.btn_bill.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_bill.setObjectName("btn_bill")
        self.btn_request = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_request.setGeometry(QtCore.QRect(22, 411, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_request.setFont(font)
        self.btn_request.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_request.setObjectName("btn_request")
        self.btn_staff = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_staff.setGeometry(QtCore.QRect(22, 462, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_staff.setFont(font)
        self.btn_staff.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_staff.setObjectName("btn_staff")
        self.btn_report = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_report.setGeometry(QtCore.QRect(22, 513, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_report.setFont(font)
        self.btn_report.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_report.setObjectName("btn_report")
        self.btn_history = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_history.setGeometry(QtCore.QRect(22, 564, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_history.setFont(font)
        self.btn_history.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_history.setObjectName("btn_history")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(2, 890, 279, 3))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btn_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_profile.setGeometry(QtCore.QRect(22, 903, 241, 48))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_profile.setFont(font)
        self.btn_profile.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_profile.setObjectName("btn_profile")
        self.btn_logOut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_logOut.setGeometry(QtCore.QRect(22, 950, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logOut.setFont(font)
        self.btn_logOut.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px 15px;\n"
"    color: #4A4A4A;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.btn_logOut.setObjectName("btn_logOut")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(17, 22, 255, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(280, 1, 1170, 2000))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page)
        self.tableWidget.setGeometry(QtCore.QRect(20, 550, 1121, 400))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(410, 20, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit.setGeometry(QtCore.QRect(20, 175, 260, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:1px solid #e0e0e0;\n"
"border-radius:12px;\n"
"padding:8px;\n"
"qproperty-alignment: AlignCenter;\n"
"color:#9028BD; \n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 175, 260, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border:1px solid #e0e0e0;\n"
"border-radius:12px;\n"
"padding:8px;\n"
"qproperty-alignment: AlignCenter;\n"
"color:#9028BD; \n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 175, 260, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border:1px solid #e0e0e0;\n"
"border-radius:12px;\n"
"padding:8px;\n"
"qproperty-alignment: AlignCenter;\n"
"color:#9028BD; \n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_4.setGeometry(QtCore.QRect(890, 175, 251, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border:1px solid #e0e0e0;\n"
"border-radius:12px;\n"
"padding:8px;\n"
"qproperty-alignment: AlignCenter;\n"
"color:#9028BD; \n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(parent=self.page)
        self.label_4.setGeometry(QtCore.QRect(427, 380, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        Main_Admin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main_Admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1468, 21))
        self.menubar.setObjectName("menubar")
        Main_Admin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main_Admin)
        self.statusbar.setObjectName("statusbar")
        Main_Admin.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Admin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main_Admin)

    def retranslateUi(self, Main_Admin):
        _translate = QtCore.QCoreApplication.translate
        Main_Admin.setWindowTitle(_translate("Main_Admin", "Admin"))
        self.btn_home.setText(_translate("Main_Admin", "Trang chủ"))
        self.btn_room.setText(_translate("Main_Admin", "Phòng"))
        self.btn_customer.setText(_translate("Main_Admin", "Khách thuê"))
        self.btn_contract.setText(_translate("Main_Admin", "Hợp đồng"))
        self.btn_eIndex.setText(_translate("Main_Admin", "Điện nước"))
        self.btn_bill.setText(_translate("Main_Admin", "Hóa đơn"))
        self.btn_request.setText(_translate("Main_Admin", "Yêu cầu"))
        self.btn_staff.setText(_translate("Main_Admin", "Nhân viên"))
        self.btn_report.setText(_translate("Main_Admin", "Báo cáo"))
        self.btn_history.setText(_translate("Main_Admin", "Lịch sử "))
        self.btn_profile.setText(_translate("Main_Admin", "Trang cá nhân"))
        self.btn_logOut.setText(_translate("Main_Admin", "Đăng xuất"))
        self.label.setText(_translate("Main_Admin", "Quản lý phòng trọ    <"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main_Admin", "Phòng"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main_Admin", "Nội dung"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Main_Admin", "Thời gian gửi"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Main_Admin", "Trạng thái"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Main_Admin", "Thao tác"))
        self.label_2.setText(_translate("Main_Admin", "<html><head/><body><p><span style=\" color:#9028bd;\">TỔNG QUAN HỆ THỐNG</span></p></body></html>"))
        self.lineEdit.setText(_translate("Main_Admin", "100"))
        self.label_3.setText(_translate("Main_Admin", "Tổng số phòng"))
        self.label_4.setText(_translate("Main_Admin", "<html><head/><body><p><span style=\" color:#5d5fef;\">Yêu cầu sửa chữa mới nhất</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Admin = QtWidgets.QMainWindow()
    ui = Ui_Main_Admin()
    ui.setupUi(Main_Admin)
    Main_Admin.show()
    sys.exit(app.exec())
