# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DangNhap(object):
    def setupUi(self, DangNhap):
        DangNhap.setObjectName("DangNhap")
        DangNhap.resize(526, 570)
        self.centralwidget = QtWidgets.QWidget(parent=DangNhap)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 60, 421, 431))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 25px;\n"
"border: 1px solid #000000;")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 201, 31))
        self.label_2.setStyleSheet("font-family: \"Arial\";\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"color: black;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-family: \"Arial\";\n"
"font-size: 13px;\n"
"color: black;\n"
"border: none;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(180, 140, 71, 31))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font-family: \"Arial\";\n"
"font-size: 13px;\n"
"color: black;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.lne_user = QtWidgets.QLineEdit(parent=self.widget)
        self.lne_user.setGeometry(QtCore.QRect(50, 90, 331, 41))
        self.lne_user.setStyleSheet("background-color: #f1f3f5;\n"
"border: 1px solid #dcdfe3;\n"
"border-radius: 12px;\n"
"padding: 10px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"border: none;")
        self.lne_user.setObjectName("lne_user")
        self.lne_password = QtWidgets.QLineEdit(parent=self.widget)
        self.lne_password.setGeometry(QtCore.QRect(50, 180, 331, 41))
        self.lne_password.setStyleSheet("background-color: #f1f3f5;\n"
"border: 1px solid #dcdfe3;\n"
"border-radius: 12px;\n"
"padding: 10px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"border: none;")
        self.lne_password.setObjectName("lne_password")
        self.rad_admin = QtWidgets.QRadioButton(parent=self.widget)
        self.rad_admin.setGeometry(QtCore.QRect(60, 240, 131, 20))
        self.rad_admin.setStyleSheet("border: None;\n"
"input[type=\"radio\"] {\n"
"  accent-color: purple;\n"
"}\n"
"")
        self.rad_admin.setObjectName("rad_admin")
        self.rad_staff = QtWidgets.QRadioButton(parent=self.widget)
        self.rad_staff.setGeometry(QtCore.QRect(60, 270, 100, 20))
        self.rad_staff.setStyleSheet("border: None")
        self.rad_staff.setObjectName("rad_staff")
        self.btn_login = QtWidgets.QPushButton(parent=self.widget)
        self.btn_login.setGeometry(QtCore.QRect(50, 310, 331, 41))
        self.btn_login.setStyleSheet("background-color: #9028BD;\n"
"border: 1px solid #dcdfe3;\n"
"border-radius: 12px;\n"
"padding: 10px;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"border: none;")
        self.btn_login.setObjectName("btn_login")
        self.btn_forgetpw = QtWidgets.QPushButton(parent=self.widget)
        self.btn_forgetpw.setGeometry(QtCore.QRect(60, 360, 113, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.btn_forgetpw.setFont(font)
        self.btn_forgetpw.setStyleSheet("border: None;\n"
"color: #3B82F6")
        self.btn_forgetpw.setObjectName("btn_forgetpw")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: \"Arial\";\n"
"font-size: 17px;\n"
"font-weight: bold;\n"
"color: #9028BD;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label.raise_()
        self.widget.raise_()
        DangNhap.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DangNhap)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 21))
        self.menubar.setObjectName("menubar")
        DangNhap.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=DangNhap)
        self.statusbar.setObjectName("statusbar")
        DangNhap.setStatusBar(self.statusbar)

        self.retranslateUi(DangNhap)
        QtCore.QMetaObject.connectSlotsByName(DangNhap)

    def retranslateUi(self, DangNhap):
        _translate = QtCore.QCoreApplication.translate
        DangNhap.setWindowTitle(_translate("DangNhap", "MainWindow"))
        self.label_2.setText(_translate("DangNhap", "Vui lòng đăng nhập để tiếp tục"))
        self.label_3.setText(_translate("DangNhap", "Tên đăng nhập"))
        self.label_4.setText(_translate("DangNhap", "Mật khẩu"))
        self.lne_user.setText(_translate("DangNhap", "Nhập tài khoản của bạn ..."))
        self.lne_password.setText(_translate("DangNhap", "..."))
        self.rad_admin.setText(_translate("DangNhap", "  Chủ trọ (Admin)"))
        self.rad_staff.setText(_translate("DangNhap", "  Nhân viên"))
        self.btn_login.setText(_translate("DangNhap", "ĐĂNG NHẬP"))
        self.btn_forgetpw.setText(_translate("DangNhap", "Quên mật khẩu ?"))
        self.label.setText(_translate("DangNhap", "HỆ THỐNG QUẢN LÝ PHÒNG TRỌ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DangNhap = QtWidgets.QMainWindow()
    ui = Ui_DangNhap()
    ui.setupUi(DangNhap)
    DangNhap.show()
    sys.exit(app.exec())
