# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(1440, 1024)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        Login.setFont(font)
        Login.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.lne_sign = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lne_sign.setGeometry(QtCore.QRect(536, 362, 347, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lne_sign.setFont(font)
        self.lne_sign.setFrame(False)
        self.lne_sign.setObjectName("lne_sign")
        self.lne_pw = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lne_pw.setGeometry(QtCore.QRect(547, 458, 347, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lne_pw.setFont(font)
        self.lne_pw.setFrame(False)
        self.lne_pw.setObjectName("lne_pw")
        self.rd_admin = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rd_admin.setGeometry(QtCore.QRect(540, 519, 20, 20))
        self.rd_admin.setText("")
        self.rd_admin.setObjectName("rd_admin")
        self.rd_nv = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rd_nv.setGeometry(QtCore.QRect(540, 571, 20, 20))
        self.rd_nv.setText("")
        self.rd_nv.setObjectName("rd_nv")
        self.btn_sign = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_sign.setEnabled(True)
        self.btn_sign.setGeometry(QtCore.QRect(520, 629, 400, 48))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sign.setFont(font)
        self.btn_sign.setStyleSheet("QPushButton {\n"
"    background-color: rgba(144, 40, 221, 230);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(144, 40, 221, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(120, 30, 190, 255);\n"
"}")
        self.btn_sign.setObjectName("btn_sign")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 30))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.btn_sign.setText(_translate("Login", "ĐĂNG NHẬP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
